//
// Generated file, do not edit! Created by opp_msgc 4.1 from messages/application/CCWSApplPkt.msg.
//

#ifndef _CCWSAPPLPKT_M_H_
#define _CCWSAPPLPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/application/CCWSApplPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet CCWSAppPkt {
 *     int id;
 *     double x;
 *     double y;
 *     double speed;
 *     double angle;
 *     double width;
 *     double length;
 *     double utc;
 * }
 * </pre>
 */
class CCWSAppPkt : public ::cPacket
{
  protected:
    int id_var;
    double x_var;
    double y_var;
    double speed_var;
    double angle_var;
    double width_var;
    double length_var;
    double utc_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CCWSAppPkt&);

  public:
    CCWSAppPkt(const char *name=NULL, int kind=0);
    CCWSAppPkt(const CCWSAppPkt& other);
    virtual ~CCWSAppPkt();
    CCWSAppPkt& operator=(const CCWSAppPkt& other);
    virtual CCWSAppPkt *dup() const {return new CCWSAppPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id_var);
    virtual double getX() const;
    virtual void setX(double x_var);
    virtual double getY() const;
    virtual void setY(double y_var);
    virtual double getSpeed() const;
    virtual void setSpeed(double speed_var);
    virtual double getAngle() const;
    virtual void setAngle(double angle_var);
    virtual double getWidth() const;
    virtual void setWidth(double width_var);
    virtual double getLength() const;
    virtual void setLength(double length_var);
    virtual double getUtc() const;
    virtual void setUtc(double utc_var);
};

inline void doPacking(cCommBuffer *b, CCWSAppPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CCWSAppPkt& obj) {obj.parsimUnpack(b);}


#endif // _CCWSAPPLPKT_M_H_
